/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgeVerificationDialog: typeof import('./src/components/AgeVerificationDialog.vue')['default']
    CheckoutDialog: typeof import('./src/components/CheckoutDialog.vue')['default']
    CustomDialog: typeof import('./src/components/CustomDialog.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ImportantNotice: typeof import('./src/components/ImportantNotice.vue')['default']
    IOcticonAlert24: typeof import('~icons/octicon/alert24')['default']
    IOcticonApps24: typeof import('~icons/octicon/apps24')['default']
    IOcticonArchive24: typeof import('~icons/octicon/archive24')['default']
    IOcticonArrowLeft16: typeof import('~icons/octicon/arrow-left16')['default']
    IOcticonCalendar16: typeof import('~icons/octicon/calendar16')['default']
    IOcticonCheck16: typeof import('~icons/octicon/check16')['default']
    IOcticonChevronDown16: typeof import('~icons/octicon/chevron-down16')['default']
    IOcticonChevronRight24: typeof import('~icons/octicon/chevron-right24')['default']
    IOcticonChevronUp16: typeof import('~icons/octicon/chevron-up16')['default']
    IOcticonCode24: typeof import('~icons/octicon/code24')['default']
    IOcticonDash16: typeof import('~icons/octicon/dash16')['default']
    IOcticonDownload16: typeof import('~icons/octicon/download16')['default']
    IOcticonEye24: typeof import('~icons/octicon/eye24')['default']
    IOcticonEyeClosed24: typeof import('~icons/octicon/eye-closed24')['default']
    IOcticonFileAdded24: typeof import('~icons/octicon/file-added24')['default']
    IOcticonFileMedia24: typeof import('~icons/octicon/file-media24')['default']
    IOcticonGear24: typeof import('~icons/octicon/gear24')['default']
    IOcticonGrabber16: typeof import('~icons/octicon/grabber16')['default']
    IOcticonHistory16: typeof import('~icons/octicon/history16')['default']
    IOcticonHistory24: typeof import('~icons/octicon/history24')['default']
    IOcticonInfo24: typeof import('~icons/octicon/info24')['default']
    IOcticonPlus16: typeof import('~icons/octicon/plus16')['default']
    IOcticonPlusCircle16: typeof import('~icons/octicon/plus-circle16')['default']
    IOcticonPlusCircle24: typeof import('~icons/octicon/plus-circle24')['default']
    IOcticonReply16: typeof import('~icons/octicon/reply16')['default']
    IOcticonSortDesc24: typeof import('~icons/octicon/sort-desc24')['default']
    IOcticonStarFill16: typeof import('~icons/octicon/star-fill16')['default']
    IOcticonSync24: typeof import('~icons/octicon/sync24')['default']
    IOcticonTrash24: typeof import('~icons/octicon/trash24')['default']
    IOcticonUpload16: typeof import('~icons/octicon/upload16')['default']
    IOcticonX24: typeof import('~icons/octicon/x24')['default']
    IOcticonXCircleFill16: typeof import('~icons/octicon/x-circle-fill16')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    MultiSelector: typeof import('./src/components/MultiSelector.vue')['default']
    Popup: typeof import('./src/components/Popup.vue')['default']
    ProductAdminItem: typeof import('./src/components/ProductAdminItem.vue')['default']
    ProductRegisterItem: typeof import('./src/components/ProductRegisterItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TermFilter: typeof import('./src/components/TermFilter.vue')['default']
    TermFilterGroup: typeof import('./src/components/TermFilterGroup.vue')['default']
  }
}
